// Function to send the request to the API and get obstacle positions
/**
 * Fetches the positions of obstacles for the game from an API.
 *
 * @async
 * @function getObstaclePositions
 * @param {Object} gameOptions - The game options, which include details such as the game level and size.
 * @param {Object} player - The player's current position, used to avoid placing obstacles near the player.
 * @param {Array} matrix - The game matrix, which represents the current state of the game board.
 * @returns {Array} The positions of the obstacles generated by the API. If an error occurs, returns an empty array.
 */
export async function getObstaclePositions(gameOptions, player, matrix) {
    try {
        // API endpoint
        const apiUrl = "https://6n3kiasb1i.execute-api.us-east-1.amazonaws.com/generate-obstacles";

        // Prepare the request body
        const requestBody = {
            gameOptions: gameOptions,
            player: {
                posX: player.posX,
                posY: player.posY,
            },
            matrix: matrix
        };

        // Make the POST request
        const response = await fetch(apiUrl, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(requestBody)
        });

        // Parse the JSON response
        const data = await response.json();

        return data;
    } catch (error) {
        console.error("Error fetching obstacle positions:", error);
        return [];
    }
}